<?php


namespace App\Admin\Grid;


use App\Models\Employee;
use App\Models\Project;
use Encore\Admin\Grid;

class AllocateGrid extends Grid
{
    public function build()
    {
        return parent::build(); // TODO: Change the autogenerated stub
    }

    public function applyFilter($toArray = true)
    {
        $collection = parent::applyFilter($toArray);
        // @todo add more info
        $projectIds = [];
        $employeeIds = [];
        foreach ($collection as $item) {
            $projectIds[$item->project_id] = $item->project_id;
            $employeeIds[$item->employee_id] = $item->employee_id;
        }
        $projects = [];
        $employees = [];
        if (count($projectIds)) {
            $projects = Project::query()->whereIn('id', $projectIds)
                ->get()->pluck('code', 'id')->toArray();
        }
        if (count($employeeIds)) {
            $employees = Employee::query()->whereIn('id', $employeeIds)
                ->get()->pluck('email', 'id')->toArray();
        }
        foreach ($collection as $item) {
            if (isset($employees[$item->employee_id])) {
                $item->employee_acc = $employees[$item->employee_id];
            }
            if (isset($projects[$item->project_id])) {
                $item->project_code = $projects[$item->project_id];
            }
        }

        return $collection;
    }
}
